import type { ThemeEntry } from '~/types/theme';

export interface CssOptions {
  includeTailwind?: boolean;
  includeNuxtUI?: boolean;
}

export function generateCss(
  themes: ThemeEntry[],
  defaultThemeName: string,
  prefix: string,
  options: CssOptions = {}
): string {
  const defaultTheme = themes.find(t => t.name === defaultThemeName) ?? themes[0];
  if (!defaultTheme) return '';

  const lines: string[] = ['/* Generated by Color Theme Studio */'];

  // Add Tailwind CSS v4 imports if enabled
  if (options.includeTailwind) {
    lines.push('', '@import "tailwindcss";');
    if (options.includeNuxtUI) {
      lines.push('@import "@nuxt/ui";');
    }
    lines.push('', '@theme {');
    for (const [shade, color] of Object.entries(defaultTheme.shades)) {
      lines.push(`  --${prefix}-${shade}: ${color};`);
    }
    lines.push('}');
  }

  // Add the :root block with theme colors
  lines.push('', ':root {');
  for (const [shade, color] of Object.entries(defaultTheme.shades)) {
    lines.push(`  --${prefix}-${shade}: ${color};`);
  }
  // Add Nuxt UI integration to the same :root block if enabled
  if (options.includeNuxtUI) {
    lines.push(`  --ui-primary: var(--${prefix}-500);`);
  }
  lines.push('}');

  for (const theme of themes) {
    lines.push('', `.theme.${theme.name} {`);
    for (const [shade, color] of Object.entries(theme.shades)) {
      lines.push(`  --${prefix}-${shade}: ${color};`);
    }
    lines.push('}');
  }

  lines.push('');
  return lines.join('\n');
}
