import type { ThemeEntry } from '~/types/theme';

export function generateJs(themes: ThemeEntry[], defaultThemeName: string): string {
  const themeNames = themes.map(t => t.name);
  const themeColors: Record<string, string> = {};
  for (const theme of themes) {
    const shades = Object.entries(theme.shades);
    themeColors[theme.name] =
      theme.shades['500'] ??
      shades[Math.floor(shades.length / 2)]?.[1] ??
      shades[0]?.[1] ??
      '#000000';
  }

  const themesLiteral = JSON.stringify(themeNames);
  const themeColorsLiteral = JSON.stringify(themeColors, null, 2);
  const defaultLiteral = JSON.stringify(defaultThemeName);
  const storageKeyLiteral = JSON.stringify('user-theme');

  return `/*!
 * Generated by Color Theme Studio
 * Themes : ${themeNames.join(', ')}
 * Default: ${defaultThemeName}
 */
(function () {
  var STORAGE_KEY = ${storageKeyLiteral};
  var themes = ${themesLiteral};
  var themeColors = ${themeColorsLiteral};
  var defaultTheme = ${defaultLiteral};

  function applyTheme(name) {
    var resolved = (name && themes.indexOf(name) !== -1) ? name : defaultTheme;
    var html = document.documentElement;
    for (var i = 0; i < themes.length; i++) { html.classList.remove(themes[i]); }
    html.classList.remove('theme');
    html.classList.add('theme', resolved);
    try { localStorage.setItem(STORAGE_KEY, resolved); } catch (e) {}
    html.dispatchEvent(new CustomEvent('themechange', { bubbles: false, detail: { theme: resolved } }));
  }

  function getCurrentTheme() {
    var html = document.documentElement;
    for (var i = 0; i < themes.length; i++) {
      if (html.classList.contains(themes[i])) return themes[i];
    }
    return defaultTheme;
  }

  function getThemes() {
    return themes.map(function (name) { return { name: name, color: themeColors[name] }; });
  }

  (function init() {
    var saved;
    try { saved = localStorage.getItem(STORAGE_KEY); } catch (e) {}
    applyTheme(saved && themes.indexOf(saved) !== -1 ? saved : defaultTheme);
  })();

  window.ColorTheme = { change: applyTheme, getThemes: getThemes, getCurrentTheme: getCurrentTheme };
})();
`;
}
