import type { ThemeEntry } from '~/types/theme';

export function generateTypes(themes: ThemeEntry[]): string {
  const themeNames = themes.map(t => t.name);
  const themeUnion = themeNames.map(name => `'${name}'`).join(' | ');

  return `/**
 * Generated by Color Theme Studio
 */

export type ThemeName = ${themeUnion};

export interface ThemeInfo {
  name: ThemeName;
  color: string;
}

export interface ColorThemeAPI {
  change(name: ThemeName): void;
  getThemes(): ThemeInfo[];
  getCurrentTheme(): ThemeName;
}

export interface ThemeChangeEvent extends CustomEvent {
  detail: { theme: ThemeName };
}

declare global {
  interface Window { ColorTheme: ColorThemeAPI; }
  interface HTMLElementEventMap { themechange: ThemeChangeEvent; }
}

export {};
`;
}
